### ISSUE TITLE
Recurring Example

### ISSUE THREAD

**Issue by vicenterusso** [alexobviously/secretary#4]
How does it behavior in background mode, when app is opened but not focused?

**Comment by alexobviously** [comment]
I assume you are talking about using this in a flutter app - this is just a dart package so it doesn't explicitly have an opinion on that. But in general, I believe if you want any code to continue running when a flutter app is backgrounded, you need to put it in a background isolate. See: https://docs.flutter.dev/packages-and-plugins/background-processes

**Comment by alexobviously** [comment]
I'm going to close this issue, but let me know if you need any support.
