### ISSUE TITLE
Would this work well with network requests?

### ISSUE THREAD

**Issue by mark8044** [alexobviously/secretary#5]
This package looks very interesting.  I was thinking of putting network requests into a secretary queue but would only want the next request to execute once the previous request completed WITH a response, so the response must come back before the next item is started.   Reading through the documentation I'm not exactly sure if that is possible?

This is what I've tried so far with complete fail

```
final networkSecretary = Secretary(
  validator: (Response response) => response.statusCode == 200 ? response : response, // for now just return everything back
  maxAttempts: 3, // retry up to 5 times
);
```

```
      networkSecretary.add(
          123,
            () => dio.get(myUrl)
      );
      _res = await networkSecretary.waitForResult(123);
```

But it seems no results are actually passed, and Im not even sure this is queuing and waiting for a result before attempting the next network request

**Comment by mark8044** [comment]
Nevermind, the answer is YES.  After some playing around I figured it out, in my case the problem was with the validator

**Comment by alexobviously** [comment]
Haha, glad you answered your own question, but yes it was definitely designed with this sort of thing in mind. If you have any more issues feel free to ask!
